import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1, 
    marginTop: 25,
  },
  scrollContent: {
    flexGrow: 1,
    paddingVertical: 20,
    paddingHorizontal: 20,      
  },
  card: {
    width: '100%',
    height: '100%',
    backgroundColor: '#deffe4f1',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 10,
    elevation: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    width: '80%',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 15,
  },
  modalOption: {
    paddingVertical: 10,
    width: '100%',
    alignItems: 'center',
  },
  modalOptionText: {
    fontSize: 16,
    color: '#333',
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    color: '#1B7F4C',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 17,
    color: '#666',
    marginBottom: 20,
    textAlign: 'center',
  },
  section: {
    width: '100%',
    marginBottom: 15,
  },
  label: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#333',
  },
  dropdown: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  dropdownText: {
    fontSize: 14,
    color: '#333',
  },
  dropdownArrow: {
    fontSize: 16,
    color: '#999',
    marginLeft: 6,
  },
  roleContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  roleButton: {
    width: '47%',
    borderWidth: 2,
    borderColor: '#ddd',
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 15,
    alignItems: 'center',
    marginBottom: 13,
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  roleButtonSelected: {
    borderColor: '#1B7F4C',
    backgroundColor: '#E6F5EC',
  },
  roleIcon: {
    width: 30,
    height: 29,
    marginRight: 8,
    resizeMode: 'contain',
  },
  roleText: {
    fontSize: 18,
    textAlign: 'center',
    marginTop: 5,
    color: '#333',
    flexWrap: 'wrap',
    textAlign: 'center',
  },
  roleTextSelected: {
    color: '#1B7F4C',
    fontWeight: '600',
  },
  farmerButton: {
    alignContent: 'center',
    gap: 5,
  },
  retailerButton: {
    gap: 12,
  },
  phoneInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#fff',
  },
  loginButton: {
    backgroundColor: '#1B7F4C',
    paddingVertical: 15,
    borderRadius: 25,
    alignItems: 'center',
    width: '100%',
    marginTop: 15,
  },
  loginButtonDisabled: {
    backgroundColor: '#A5D6BA',
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});